"""Synthesis agent that aggregates verified evidence into an executive research brief with citations."""

from __future__ import annotations

from typing import Dict, List
from app.agents.state import AgentLog, ResearchState


class SynthesisAgent:
    """Synthesizes verified claims and evidence into a structured markdown report."""

    def synthesize(self, state: ResearchState) -> ResearchState:
        """Construct the final research report."""
        query = state.user_query
        claims = state.extracted_claims
        evidence_items = state.verified_evidence
        results = state.search_results

        # Source index mapping for citation numbers [1], [2], ...
        source_map: Dict[str, int] = {}
        source_list: List[Dict[str, str]] = []

        for r in results:
            if r.document_id not in source_map:
                idx = len(source_list) + 1
                source_map[r.document_id] = idx
                source_list.append({"index": str(idx), "id": r.document_id, "title": r.title})

        # Format Findings
        findings_lines: List[str] = []
        for claim in claims[:5]:  # Top 5 core claims
            cite_idx = source_map.get(claim.document_id or "", 1)
            findings_lines.append(f"- {claim.text} [[{cite_idx}]](#ref-{cite_idx})")

        if not findings_lines:
            findings_lines.append(
                "- No verified claims could be extracted for this query with the current sources."
            )

        # References block
        references_lines: List[str] = []
        for s in source_list:
            references_lines.append(
                f"<a id=\"ref-{s['index']}\"></a>[{s['index']}] **{s['title']}** (`{s['id']}`)"
            )

        report = f"""# Research Intelligence Brief

**Topic**: {query}

## Executive Summary
This report presents evidence-backed findings synthesized by autonomous agents using verified sources.

## Key Verified Findings
{chr(10).join(findings_lines)}

## Evidence & Citations
{chr(10).join(references_lines) if references_lines else "No external sources cited."}

---
*Report generated by Agentic Research Intelligence Platform.*
"""

        state.final_report = report.strip()
        state.logs.append(
            AgentLog(
                agent_name="SynthesisAgent",
                action="synthesize_report",
                details={
                    "citations_count": len(source_list),
                    "claims_synthesized": len(findings_lines),
                },
            )
        )

        return state
